### ISSUE TITLE
Правка один 

### ISSUE THREAD

**Issue by DriveAthlete** [anjerukare/edu_chess-game#3]
https://github.com/anjerukare/edu_chess-game/blob/80c3f555d5c9627b4b96b7726695aca4bfc752ed/core/src/edu/anjerukare/screens/listeners/BoardListener.java#L168

Вынести в общее место данный кусок кода 
```
boardView.resetTileStates(); 
Point point = boardView.getPointForPiece(boardView.selectedPiece);
```

**Comment by anjerukare** [comment]
Когда мы смотрели в офисе код, не заметил сразу: строчка `boardView.resetTileStates();` должна находиться в каждом блоке `case`, так как метод `resetTileStates()` изменяет состояние, которое проверяется в switch-конструкции. Поэтому возможно вынести лишь одну строчку – `Point point = boardView.getPointForPiece(boardView.selectedPiece);`.
